# -*- coding: utf-8 -*-
"""LinkedIn_Profile_Optimizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mAR-_4UeeY2mghYaQyrMt3zqRvvgUY0
"""

!pip install notebook

!pip install openai

import openai
import requests
from PIL import Image
from io import BytesIO

# Configurar la API key de OpenAI
api_key = "API_KEY"

openai.api_key = api_key

"""## Generar contenido para LinkedIn"""

def generate_text(prompt, model="gpt-4", temperature=0.7):
    """Genera texto basado en el prompt utilizando la API de OpenAI."""
    response = openai.ChatCompletion.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature
    )
    return response["choices"][0]["message"]["content"]

# Ejemplo de uso
prompt = "Escribe una descripción atractiva para un perfil de LinkedIn de un especialista en IA y gestión de riesgos."
linkedin_bio = generate_text(prompt)
print(linkedin_bio)

"""## Generacion de imagenes (DALL E)"""

def generate_image(prompt, model="dall-e-2"):
    """Genera una imagen basada en el prompt utilizando DALL·E."""
    response = openai.Image.create(
        prompt=prompt,
        model=model,
        n=1,
        size="1024x1024"
    )
    image_url = response["data"][0]["url"]

    # Descargar y mostrar la imagen
    response = requests.get(image_url)
    img = Image.open(BytesIO(response.content))
    return img

# Ejemplo de uso
prompt_image = "Diseña un banner profesional para un perfil de LinkedIn de un especialista en ciencia de datos."
banner_image = generate_image(prompt_image)
banner_image.show()

print("Perfil ANTES de la optimización:")
print("Juan Pérez - Ingeniero en IA")

print("\nPerfil DESPUÉS de la optimización:")
optimized_bio = generate_text("Redacta una descripción profesional para un ingeniero en IA destacando sus logros y habilidades.")
print(optimized_bio)